spring:
  jpa:
    hibernate:
      ddl-auto:
        update
  datasource:
    url:
#      jdbc:postgresql://ep-weathered-rice-648785.eu-central-1.aws.neon.tech/neondb
      jdbc:mysql://localhost:3306/jl_db
    username:
#      mohamedham72
      root
    password:
#      AT9kiHQ4bMOw
      V@ste789
#      Massaq51354
    driver-class-name:
#      org.postgresql.Driver
      com.mysql.cj.jdbc.Driver


server:
  port: 8090
spring.jpa.show-sql: true