spring:
  jpa:
    hibernate:
      ddl-auto:
        create
  datasource:
    url:
      jdbc:postgresql://ep-weathered-rice-648785.eu-central-1.aws.neon.tech/neondb
#      jdbc:mysql://localhost:3306/jl_db
    username:
      mohamedham72
#      root
    password:
      AT9kiHQ4bMOw
#      V@ste789
#      Massaq51354
    driver-class-name:
      org.postgresql.Driver
#      com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    username: mohamedham72@gmail.com
    password: yhbnfisjibqkodxl
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true



server:
  port: 8090
spring.jpa.show-sql: true

twilio:
  account-sid: AC2e6a7c5d18e16fead92005b1369f3e58
  auth-token: ea2cfae727861197da12a38aa917d61e
  trial-phone-number: +12543303862

