spring:
  jpa:
    hibernate:
      ddl-auto:
        create
  datasource:
    url:
      jdbc:mysql://localhost:3306/jl_db
    username:
      root
    password:

    driver-class-name:
      com.mysql.cj.jdbc.Driver

server:
  port: 8090
spring.jpa.show-sql: true