//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.21 at 02:35:03 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.jl_entities.com/creancierservice", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jl_entities.creancierservice;
